### ISSUE TITLE
Dashboard does not automatically reload on new day

### ISSUE THREAD

**Issue by krishpop** [Tatz884/RescueTime-Obsidian#3]
I've tried to use this in my obsidian notebook and after one day I found that the dashboard would not reload to start again on the new day. It's possible that there is an error in refreshing the codeblock to generate the new embedded dashboard, but I had to manually disable and re-enable the extension for it to reload.

**Comment by krishpop** [comment]
Here is an example of how it appears for instance
 
![Screenshot 2024-01-11 at 9 49 21 AM](https://github.com/Tatz884/RescueTime-Obsidian/assets/5395510/d9b73813-6742-44bb-8fe7-71f7ef11c742)

**Comment by Tatz884** [comment]
Thank you for your raising up the issue! To understand the problem better, would you be willing to answer the following questions?

Is the problem that the codeblock on the left shows the data for 01/10 even though you specified 01/11? Or, is the problem that the dashboard on the right shows the data of yesterday even though you screencaptured it on today?

**Comment by Tatz884** [comment]
I believe this issue is fixed in version 0.2.6. If not, please kindly reopen the issue. Thank you!
